export const action_types = {
  POST_INVOICE_SUCCESS: 'POST_IVOICE',
  GET_INVOICE_SUCCESS: 'GET_INVOICE_SUCCESSL',
  INVOICE_INPUTS_CHANGE_HANDLE: 'INVOICE_INPUTS_CHANGE_HANDLE',
  GET_INVOICE_BY_ID_SUCCESS: 'GET_INVOICE_BY_ID_SUCCESS',
  HANDLE_UPDATE_INVOICE_RESPONSE: 'HANDLE_UPDATE_INVOICE_RESPONSE',
  DELETE_INVOICE_SUCCESS: 'DELETE_INVOICE_SUCCESS'
};
