export const action_types = {
  POST_INVOICE_SUCCESS: 'POST_IVOICE',
  GET_INVOICE_SUCCESS: 'GET_INVOICE_SUCCESSL',
  INVOICE_INPUTS_CHANGE_HANDLE: 'INVOICE_INPUTS_CHANGE_HANDLE',
  GET_INVOICE_BY_ID_SUCCESS: 'GET_INVOICE_BY_ID_SUCCESS',
};
