export const action_types = {
  SET_SELECTED_CUSTOMER: 'SET_SELECTED_CUSTOMER',
  ADD_PRODUCT_TO_QOUTATION: 'ADD_PRODUCT_TO_QOUTATION',
  REMOVE_PRODUCT_FROM_QOUTATION: 'REMOVE_PRODUCT_FROM_QOUTATION',
  GET_CUSTOMER_INVOICE_PRODUCTS_SUCCESS:
    'GET_CUSTOMER_INVOICE_PRODUCTS_SUCCESS',
};
