const action_types = {
  ADD_FETCHED_PRODUCT: 'ADD_FETCHED_PRODUCT',
  APPEND_POSTED_PRODUCT: 'APPEND_POSTED_PRODUCT',
  TOGGLE_PRODUCT_LOADER: 'TOGGLE_PRODUCT_LOADER',
  APPEND_POSTED_PRODUCT_SUCCESS: 'APPEND_POSTED_PRODUCT_SUCCESS',
  APPEND_POSTED_PRODUCT_ERROR: 'APPEND_POSTED_PRODUCT_ERROR',
  FETCH_PRODUCT_DETAILS: 'FETCH_PRODUCT_DETAILS',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  GET_CUSTOMER_INVOICE_PRODUCTS_SUCCESS:
    'GET_CUSTOMER_INVOICE_PRODUCTS_SUCCESS',
};
export default action_types;
