const action_types = {
  ADD_FETCHED_PRODUCT: 'ADD_FETCHED_PRODUCT',
  APPEND_POSTED_PRODUCT: 'APPEND_POSTED_PRODUCT',
  TOGGLE_PRODUCT_LOADER: 'TOGGLE_PRODUCT_LOADER',
  APPEND_POSTED_PRODUCT_SUCCESS: 'APPEND_POSTED_PRODUCT_SUCCESS',
  APPEND_POSTED_PRODUCT_ERROR: 'APPEND_POSTED_PRODUCT_ERROR',
};
export default action_types;
